version: "3"

networks:
  bwapp:

services:
  bwapp_server:
    container_name: bwapp_server
    build: ./docker/php-apache
    volumes:
      - ./bWAPP:/var/www/html
      - ./docker/php-apache/logs:/var/log/apache2
    ports:
      - ${APP_PORT}:80
    depends_on:
      - bwapp_mariadb
    networks:
      - bwapp
  bwapp_mariadb:
    container_name: bwapp_mariadb
    build: ./docker/mariadb
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - bwapp
